require("dotenv").config();
const express = require("express");
const cors = require("cors");
const { requestLogger } = require("./middleware/requestLogger");
const {
  getPortfolioSummary,
  getSignals,
  getTrades,
  getPortfolioHistory,
  getOpsHealth,
} = require("./connectors/mockExchangeConnector");
const config = require("./config");



const app = express();
const PORT = process.env.PORT || 4000;

// Middleware for logging and HTTP metadata.
app.use(requestLogger);
 
// Middleware for CORS configuration
app.use(
  cors({
    origin: config.corsOrigin,
  })
);

app.use(express.json());

// Route modules for the API.
const portfolioRoutes = require("./routes/portfolioRoutes");
const signalRoutes = require("./routes/signalRoutes");
const tradeRoutes = require("./routes/tradeRoutes");
const opsRoutes = require("./routes/opsRoutes");

// Portfolio summary for the current account or environment.
app.use("/api/portfolio", portfolioRoutes);
// Recent trading signals generated by strategies.
app.use("/api/signals", signalRoutes);
// Executed trades and their R-multiples.
app.use("/api/trades", tradeRoutes);
// Operational health for bots and connectivity.
app.use("/api/ops", opsRoutes);

// Simple health endpoint for monitoring.
app.get("/api/health", (req, res) => {
  res.json({
    status: "ok",
    service: "alphaopsdash-backend",
    timestamp: new Date().toISOString(),
  });
});


 
// Historical equity values for the portfolio.
app.get("/api/portfolio/history", (req, res) => {
  res.json(getPortfolioHistory());
});
  
// Starts the HTTP server only when this file is run directly.
if (require.main === module) { 
  app.listen(config.port, () => {
    console.log(`AlphaOpsDash backend listening on http://localhost:${config.port}`);
  });
}



// Exports the Express application for testing.
module.exports = app;
