require("dotenv").config();
const express = require("express");
const cors = require("cors");

const config = require("./config");
const { requestLogger } = require("./middleware/requestLogger");
const { errorHandler } = require("./middleware/errorHandler");

// Si sigues usando el conector directo para el histórico:
const { getPortfolioHistory } = require("./connectors/mockExchangeConnector");

// Route modules for the API.
const portfolioRoutes = require("./routes/portfolioRoutes");
const signalRoutes = require("./routes/signalRoutes");
const tradeRoutes = require("./routes/tradeRoutes");
const opsRoutes = require("./routes/opsRoutes");
const marketRoutes = require("./routes/marketRoutes");

const app = express();

// Middleware for logging and HTTP metadata.
app.use(requestLogger);

// Middleware for CORS configuration
app.use(
  cors({
    origin: config.corsOrigin,
  })
);

app.use(express.json());

// API routes
// Portfolio summary for the current account or environment.
app.use("/api/portfolio", portfolioRoutes);
// Recent trading signals generated by strategies.
app.use("/api/signals", signalRoutes);
// Executed trades and their R-multiples.
app.use("/api/trades", tradeRoutes);
// Operational health for bots and connectivity.
app.use("/api/ops", opsRoutes);
// Live market data (e.g. BTC price from external API).
app.use("/api/market", marketRoutes);

// Simple health endpoint for monitoring.
app.get("/api/health", (req, res) => {
  res.json({
    status: "ok",
    service: "alphaopsdash-backend",
    timestamp: new Date().toISOString(),
  });
});

// Historical equity values for the portfolio.
// (Si en el futuro mueves esto a portfolioRoutes, puedes eliminar esta ruta directa.)
app.get("/api/portfolio/history", (req, res) => {
  res.json(getPortfolioHistory());
});

// Error handling middleware (debe ir después de todas las rutas)
app.use(errorHandler);

// Starts the HTTP server only when this file is run directly.
if (require.main === module) {
  app.listen(config.port, () => {
    console.log(
      `AlphaOpsDash backend listening on http://localhost:${config.port}`
    );
  });
}

// Exports the Express application for testing.
module.exports = app;
