const express = require("express");
const cors = require("cors");
const {
  getPortfolioSummary,
  getSignals,
  getTrades,
  getPortfolioHistory,
  getOpsHealth,
} = require("./connectors/mockExchangeConnector");

const app = express();
const PORT = process.env.PORT || 4000;

// Handles CORS and JSON body parsing for API requests.
app.use(
  cors({
    origin: "http://localhost:5173",
  })
);
app.use(express.json());

// Portfolio summary for the current account or environment.
app.get("/api/portfolio", (req, res) => {
  res.json(getPortfolioSummary());
});

// Historical equity values for the portfolio.
app.get("/api/portfolio/history", (req, res) => {
  res.json(getPortfolioHistory());
});

// Recent trading signals generated by strategies.
app.get("/api/signals", (req, res) => {
  res.json(getSignals());
});

// Executed trades and their R-multiples.
app.get("/api/trades", (req, res) => {
  res.json(getTrades());
});

// Operational health for bots and connectivity.
app.get("/api/ops", (req, res) => {
  res.json(getOpsHealth());
});

// Simple health endpoint for monitoring.
app.get("/api/health", (req, res) => {
  res.json({
    status: "ok",
    service: "alphaopsdash-backend",
    timestamp: new Date().toISOString(),
  });
});

// Starts the HTTP server only when this file is run directly.
if (require.main === module) {
  app.listen(PORT, () => {
    console.log(`AlphaOpsDash backend listening on http://localhost:${PORT}`);
  });
}

// Exports the Express application for testing.
module.exports = app;
